<a href="https://colab.research.google.com/github/austinfrancisbridgerland/data_example/blob/main/Module_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
mylist = [42,99,12,6,15,9]

myarray = np.array(mylist)

myarray

array([42, 99, 12,  6, 15,  9])

In [3]:
myarray / 3

array([14., 33.,  4.,  2.,  5.,  3.])

In [4]:
myarray.reshape(-1,1)

array([[42],
       [99],
       [12],
       [ 6],
       [15],
       [ 9]])

In [13]:
np.linspace(0,100,100,endpoint = False)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [15]:
np.arange(0,100,30)

array([ 0, 30, 60, 90])

In [25]:
np.random.random()

0.982565184685201

In [27]:
myarray

array([42, 99, 12,  6, 15,  9])

In [26]:
np.argmax(myarray)

1

In [28]:
np.argmin(myarray)

3

In [29]:
np.where(myarray > 30,"big","small")

array(['big', 'big', 'small', 'small', 'small', 'small'], dtype='<U5')